function [PEST] = PEST_setup(info)

%--------------------------------------------------------------------------
PEST = PAL_AMRF_setupRF('priorAlphaRange',info.PEST_prior_alpha_range,...
    'stopCriterion',info.PEST_stop_criterion,...
    'stopRule',info.PEST_stop_rule,...
    'beta',info.PEST_beta,...
    'gamma',info.PEST_gamma,...
    'lambda',info.PEST_lambda,...
    'PF',info.PEST_PF,...
    'xMin',info.PEST_xmin,...
    'xMax',info.PEST_xmax,...
    'meanmode',info.PEST_mean_mode);
end